// eslint-disable-next-line no-unused-labels

export const productData = [
  { productId: "501", productName: "Himawan Jas Hitam", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 3.000.000", productImage: require("@/assets/img/products/mens-jas/himawan-jas-hitam.jpeg"), productImageSecond: require("@/assets/img/products/boma.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "502", productName: "Boma Jas Biru", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 4.000.000", productImage: require("@/assets/img/products/product.jpeg"), productImageSecond: require("@/assets/img/products/mens-jas/boma-jas-biru.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "503", productName: "Bakuh Jas Hitam", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 4.000.000", productImage: require("@/assets/img/products/mens-jas/bakuh-jas-hitam.jpeg"), productImageSecond: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "504", productName: "Dumuwe Jas Tuxedo", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 3.000.000", productImage: require("@/assets/img/products/mens-jas/dumuwe-jas-tuxedo.jpeg"), productImageSecond: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "508", productName: "Pawitra Jas Putih Tulang", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 2.760.000", productImage: require("@/assets/img/products/mens-jas/pawitra-jas-putih-tulang.jpeg"), productImageSecond: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "509", productName: "Sadarpa Jas Maroon", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 2.760.000", productImage: require("@/assets/img/products/product.jpeg"), productImageSecond: require("@/assets/img/products/mens-jas/sadarpa-jas-maroon.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "5010", productName: "Sena Jas Hitam", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 2.760.000", productImage: require("@/assets/img/products/mens-jas/sena-jas-hitam.jpeg"), productImageSecond: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "5011", productName: "Surdale Jas Abu-abu", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 5.600.000", productImage: require("@/assets/img/products/product.jpeg"), productImageSecond: require("@/assets/img/products/mens-jas/surdale-jas-abu-abu.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "5013", productName: "Aksamala Jas Perunggu", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 3.000.000", productImage: require("@/assets/img/products/mens-jas/aksamala-jas-perunggu.jpeg"), productImageSecond: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://tokopedia.link/iznwoSTmAAb" },
]

export const mensKemeja = [
  { productId: "501", productName: "Kemeja 1", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 3.000.000", productImage: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "502", productName: "Kemeja 2", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 4.000.000", productImage: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "503", productName: "Kemeja 3", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 4.000.000", productImage: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
]
export const mensJaket = [
  { productId: "501", productName: "Jaket 1", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 3.000.000", productImage: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "502", productName: "Jaket 2", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 4.000.000", productImage: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "503", productName: "Jaket 3", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 4.000.000", productImage: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
]
export const mensBlazer = [
  { productId: "505", productName: "Dungarees Blazer Pria", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 1.530.000", productImage: require("@/assets/img/products/mens-blazer/dungarees-blazer-pria.jpeg"), productImageSecond: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  // { productId: "502", productName: "Blazer 2", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 4.000.000", productImage: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  // { productId: "503", productName: "Blazer 3", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 4.000.000", productImage: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
]
export const mensCelana = [
  { productId: "501", productName: "Celana A", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 3.000.000", productImage: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "502", productName: "Celana B", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 4.000.000", productImage: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "503", productName: "Celana C", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 4.000.000", productImage: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
]
export const womensBlazer = [
  { productId: "5012", productName: "Wara Blazer Wanita", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 1.280.000", productImage: require("@/assets/img/products/product.jpeg"), productImageSecond: require("@/assets/img/products/womens-blazer/wara-blazer-wanita.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "506", productName: "Gayatri Blazer Wanita", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 1.400.000", productImage: require("@/assets/img/products/womens-blazer/gayatri-blazer-wanita.jpeg"), productImageSecond: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  // { productId: "507", productName: "Laksmi Blazer Wanita", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 1.280.000", productImage: require("@/assets/img/products/product.jpeg"), productImageSecond: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
]
export const womensCelanaDanRok = [
  { productId: "501", productName: "Celana 1", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 3.000.000", productImage: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "502", productName: "Celana 2", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 4.000.000", productImage: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
  { productId: "503", productName: "Celana 3", productLink: { zalora: "https://www.zalora.co.id/p/cardinal-office-wear-blazer-notch-lapel-1-button-black-3951539?catalogType=Category&listId=Jas%20%26%20Blazer", tokopedia: "https://tokopedia.link/hOK7yU1GEAb", shopee: "https://shopee.co.id/yungtailor/12183728775" }, productPrice: "Rp 4.000.000", productImage: require("@/assets/img/products/product.jpeg"), productLinkTokped: "https://shopee.co.id/yungtailor/12183728775" },
]
